### ISSUE TITLE
nice backdoor (totally not skidded off pawels from 2019)

### ISSUE THREAD

**Issue by xaxaxaxaxaxaxaxaxa** [RoyaIScar/Oldgen#1]
how are you this bad at scripting after being on this game since 2018

your backdoor/client bridge: [https://cdn.discordapp.com/attachments/793925161052667935/905149548710735933/unknown.png](url)

leaked pawels from 2019's backdoor/client bridge: [https://cdn.discordapp.com/attachments/793925161052667935/905149831406813194/unknown.png](url)

**Comment by RoyaIScar** [comment]
Me when i already said i did not make it


You are honestly the most obsessed person in the world
I already had my beef with you and you randomly say LOL EPIC BACKDOOR LOL PAWEL
After everybody already knows its his

And can i just say that i havent been on the game since 2018 i started in late 2016 and stopped playing and back in late 2018 and didnt try learning lua yet

It was only when i came back at the end of 2021 that i tried to put effort into it

If you would like to continue this pointless conversation add my discord Scar ye v2#7410

**Comment by xaxaxaxaxaxaxaxaxa** [comment]
im not "obsessed" lol
its just funny for you to call me and my friends skids but you have the ugliest code in the world

**Comment by RoyaIScar** [comment]
Firstly that makes literally no sense at all and i havent had a problem with you or youre friends for the longest time and you are still angry about something apparently but whatever thats youre own problem

**Comment by RoyaIScar** [comment]
And like i said message me on discord if you still have a problem im not argueing on github thats just cringe
